### ISSUE TITLE
Client crash and server requirement??

### ISSUE THREAD

**Issue by Gunner76th** [hancin/Fullscreen-Windowed-Minecraft#10]
[crash-2017-01-19_20.08.33-client.txt](https://github.com/hancin/Fullscreen-Windowed-Minecraft/files/719139/crash-2017-01-19_20.08.33-client.txt)
The attached client crash seems to be happening mostly on computers with NVidia graphics cards, and mostly with those using the 950 series. This crash happens during startup of the mod. 

If a user tries to connect to my server with this mod disabled then they receive the following error: https://cdn.discordapp.com/attachments/125381824842170368/271844301141573632/Screenshot_4.png
![screenshot_4](https://cloud.githubusercontent.com/assets/5566872/22147128/393a4442-ded5-11e6-9621-a751ec91357b.png) 
It would appear that for some reason, your mod is requiring that it be on both the server and the client, which is inconsistent with other GUI based mods. Since the server does not have a gui that this mod can affect, and from the best of my knowledge nothing about this mod requires information from the server in which to function, this mod should only be a client side mod. 

Can you provide some detailed information as to why this mod requires that it be loaded on both the client and the server in order for a client to be able to connect? This mod is being shipped with Sky Factory 3.

**Comment by hancin** [comment]
Hi there,

For the mod requiring to be present on servers, it is due to me not noticing a forge change that made mods be required on server & client by default unless explicitely opted out. The mod has been marked client only. **Workaround for 1.3.0**: remove the mod from the server, that should get rid of the hard requirement for clients without preventing them to login if they have it. If you want the mod to be disabled, you can also on your client set B:enableFullscreenWindowed to false in the fw.cfg file.

For the mentioned crash, I have identified an issue if the game is launched in fullscreen mode from java arguments. This should also be fixed in the new version.

Can you test this version with your settings and see if you are still experiencing the crash?
[FullscreenWindowed-1.10.2-20170120-unofficial.jar.zip](https://github.com/hancin/Fullscreen-Windowed-Minecraft/files/719674/FullscreenWindowed-1.10.2-20170120-unofficial.jar.zip)

Cheers

**Comment by Gunner76th** [comment]
I will let our user know in https://github.com/IHOC/Server/issues/4 to give this a try on his system. As for our server, that is good to know, and ill pull it off the server. Thanks for the update.

**Comment by ASL1014** [comment]
The new .jar file works as far as booting up the modpack but there is still rejection from the server with the same error.

**Comment by Gunner76th** [comment]
The mod rejection he is referencing is due to us still having the previous official release active on the server when he tested the new test build. The client no longer crashes with the new test build. 

I consider this issue resolved and will wait for you to close it once you are ready @hancin

**Comment by hancin** [comment]
I have promoted version 1.4.0 on curse to a release build containing the fixes mentioned above.

**Server admins**: your server should not have Fullscreen Windowed 1.3.0b or under in the server mod folder. I suggest removing the mod from the server as it will not affect any of your users.
**Users having the same issue**: If your client crashes due to this issue, and your server admin has the mod installed on their server, you can use this fixed "1.3.0b" version: [FullscreenWindowed-1.10.2-20170123-unofficial.zip](https://github.com/hancin/Fullscreen-Windowed-Minecraft/files/725020/FullscreenWindowed-1.10.2-20170123-unofficial.zip)

Thanks for reporting the issue 😃
